myapp/urls.py
from django.urls import path, include
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    path('post_detail/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('post_update/<int:pk>', views.PostUpdate.as_view(), name='post_update'),
    path('post_delete/<int:pk>', views.PostDelete.as_view(), name='post_delete'),
    path('post_list', views.PostList.as_view(), name='post_list'),
    path('loginuser', views.Login.as_view(), name='loginuser'),
    path('logoutuser', views.Logout.as_view(), name='logoutuser'),
    path('signupuser', views.SignUp.as_view(), name='signupuser'),
    path('like/<int:post_id>', views.Like_add, name='like'),
    path('category_list', views.CategoryList.as_view(), name='category_list'),
    path('category_detail/<str:name_en>', views.CategoryDetail.as_view(), name='category_detail'),
    path('search', views.Search, name='search'),
]

sfcproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=50)
    name_en = models.CharField('カテゴリ名英語', max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def post_count(self):
        n = Post.objects.filter(category=self).count()
        return n

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    title = models.CharField('タイトル', max_length=50)
    content = models.TextField('内容', max_length=1000)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Like(models.Model):
    post = models.ForeignKey(Post, verbose_name="投稿", on_delete=models.PROTECT)
    user = models.ForeignKey(User, verbose_name="Likeしたユーザー", on_delete=models.PROTECT)

myapp/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'category', 'thumbnail')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class LoginForm(AuthenticationForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class SearchForm(forms.Form):
    freeword = forms.CharField(min_length=1, max_length=30, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

myapp/views.py
from django.shortcuts import render, resolve_url, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from .models import Post, Like, Category
from django.urls import reverse_lazy
from .forms import PostForm, LoginForm, SignUpForm, SearchForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator

class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exception = True
    def test_func(self):
        post = Post.objects.get(id = self.kwargs['pk'])
        return post.author == self.request.user

class Index(LoginRequiredMixin, TemplateView):
    login_url = '/loginuser'
    template_name = 'myapp/index.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-created_at')
        context = {
            'post_list': post_list,
        }
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    login_url = '/loginuser'
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, '投稿しました。')
        return resolve_url('myapp:index')


class PostDetail(LoginRequiredMixin, DetailView):
    login_url = '/loginuser'
    model = Post

    def get_context_data(self, *args, **kwargs):
        detail_data = Post.objects.get(id=self.kwargs['pk'])
        category_posts = Post.objects.filter(category=detail_data.category).order_by('-created_at')[:5]

        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }
        return params

class PostUpdate(OnlyMyPostMixin, UpdateView):
    login_url = '/loginuser'
    model = Post
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request, '記事をを更新しました')
        return resolve_url('myapp:post_detail', pk=self.kwargs['pk'])

class PostDelete(OnlyMyPostMixin, DeleteView):
    login_url = '/loginuser'
    model = Post

    def get_success_url(self):
        messages.info(self.request, '記事を削除しました')
        return resolve_url('myapp:index')


class PostList(LoginRequiredMixin, ListView):
    login_url = '/loginuser'
    paginate_by = 5
    model = Post

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')

class Login(LoginView):
    form_class = LoginForm
    template_name = 'myapp/login.html'

class Logout(LoginRequiredMixin, LogoutView):
    login_url = '/loginuser'
    template_name = 'myapp/logout.html'


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'myapp/signup.html'
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.info(self.request, 'ユーザー登録をしました')
        return HttpResponseRedirect(self.get_success_url())


@login_required
def Like_add(request, post_id):
    post = Post.objects.get(id=post_id)
    is_liked = Like.objects.filter(user = request.user, post = post_id).count()
    if is_liked > 0:
        messages.info(request, 'すでにお気に入りに追加済みです')
        return redirect('myapp:post_detail', post_id)
    like = Like()
    like.user = request.user
    like.post = post
    like.save()

    messages.success(request, 'お気に入りに追加しました')
    return redirect('myapp:post_detail', post.id)


class CategoryList(LoginRequiredMixin, ListView):
    login_url = '/loginuser'
    model = Category

    def get_queryset(self):
        return Category.objects.all().order_by('-name')


class CategoryDetail(LoginRequiredMixin, DetailView):
    login_url = '/loginuser'
    model = Category
    slug_field = 'name_en'
    slug_url_kwarg = 'name_en'

    def get_context_data(self, *args, **kwargs):
        detail_data = Category.objects.get(name_en=self.kwargs['name_en'])
        category_posts = Post.objects.filter(category=detail_data.id).order_by('-created_at')

        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }

        return params


def Search(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            freeword = searchform.cleaned_data['freeword']
            searchlist = Post.objects.filter(Q(title__icontains = freeword) | Q(content__icontains = freeword))
        
        params = {
            'freeword': freeword,
            'search_list': searchlist
        }

        return render(request, 'myapp/search.html', params)

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{{ request.site.siteconfig.meta_title }}</title>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.2.0/mdb.min.css" rel="stylesheet" />
</head>

<body>
    <!-- Start your project here-->
    <header>
        <!-- Navbar -->

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <!-- Container wrapper -->
            <div class="container-fluid">
                <!-- Navbar brand -->
                <a class="navbar-brand" href="/">SelfFunClub</a>

                <!-- Toggle button -->
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'myapp:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin" target="_brank">AdminPage</a>
                        </li>
                        <!-- Navbar dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-mdb-toggle="dropdown" aria-expanded="false">
                                投稿
                            </a>
                            <!-- Dropdown menu -->
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'myapp:post_create' %}">新規投稿</a></li>
                                <li><a class="dropdown-item" href="{% url 'myapp:post_list' %}">投稿一覧</a></li>
                            </ul>
                        </li>
                        <!-- Navbar dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-mdb-toggle="dropdown" aria-expanded="false">
                                カテゴリ
                            </a>
                            <!-- Dropdown menu -->
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for item in category_list %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'myapp:category_detail' item.name_en %}">
                                        {{ item.name }}
                                    </a>
                                </li>
                                {% endfor %}
                                <hr>
                                <li><a class="dropdown-item" href="{% url 'myapp:category_list' %}">カテゴリ一覧</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-mdb-toggle="dropdown" aria-expanded="false">
                                アカウント
                            </a>
                            <!-- Dropdown menu -->
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">


                                {% if request.user.is_authenticated %}
                                <li class="dropdown-item">{{ request.user }}</li>
                                <li><a class="dropdown-item" href="{% url 'myapp:logoutuser' %}">ログアウト</a></li>
                                {% else %}
                                <li><a class="dropdown-item" href="{% url 'myapp:loginuser' %}">ログイン</a></li>
                                <li><a class="dropdown-item" href="{% url 'myapp:signupuser' %}">ユーザー登録</a></li>
                                {% endif %}
                            </ul>
                        </li>

                    </ul>
                    <!-- Left links -->

                    <!-- Search form -->
                    <form action="{% url 'myapp:search' %}" class="d-flex input-group w-auto" method="POST">
                        {% csrf_token %}
                        <input type="search" class="form-control" placeholder="Type query" aria-label="Search"
                            name="freeword" />
                        <button class="btn btn-outline-primary" type="button" data-mdb-ripple-color="dark">
                            Search
                        </button>
                    </form>
                </div>
                <!-- Collapsible wrapper -->
            </div>
            <!-- Container wrapper -->
        </nav>

        <!-- Navbar -->



    </header>
    <main class='container'>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </ul>
        {% endif %}
        {% block content %}
        {% endblock %}
    </main>
    <!-- Footer -->
    <footer class="bg-light text-center text-lg-start">
        <!-- Grid container -->
        <div class="container p-4">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Footer Content</h5>

                    <p>
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                        molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
                        voluptatem veniam, est atque cumque eum delectus sint!
                    </p>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Links</h5>

                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="#!" class="text-dark">Link 1</a>
                        </li>
                        <li>
                            <a href="#!" class="text-dark">Link 2</a>
                        </li>
                        <li>
                            <a href="#!" class="text-dark">Link 3</a>
                        </li>
                        <li>
                            <a href="#!" class="text-dark">Link 4</a>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase mb-0">Links</h5>

                    <ul class="list-unstyled">
                        <li>
                            <a href="#!" class="text-dark">Link 1</a>
                        </li>
                        <li>
                            <a href="#!" class="text-dark">Link 2</a>
                        </li>
                        <li>
                            <a href="#!" class="text-dark">Link 3</a>
                        </li>
                        <li>
                            <a href="#!" class="text-dark">Link 4</a>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            © 2020 Copyright:
            <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <!-- End your project here-->
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.2.0/mdb.min.js"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
</body>

</html>

myapp/templates/myapp/category_detail.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2 class="">{{ object.name }}</h2>
        <hr>
        <ul class="list-group">
            {% for item in category_posts %}
            <li class="list-group-item"><a href="{% url 'myapp:post_detail' item.pk %}">{{ item.title }}</a></li>
            {% endfor %}
        </ul>
        <br>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/category_list.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2 class="">カテゴリ一覧</h2>
        <br>
    </div>
</div>
<div class="row">

    {% for category in category_list %}
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">
                    <a href="{% url 'myapp:category_detail' category.name_en %}">{{ category.name }}</a>
                    &nbsp;<small>({{ category.post_count }})</small>
                </h4>
                <hr>

                {% for post in category.post_set.all|slice:":5" %}
                <p class="card-text"><a href="{% url 'myapp:post_detail' post.pk %}">{{ post.title }}</a></p>
                {% endfor %}
                <hr>
                <a href="{% url 'myapp:category_detail' category.name_en %}">このカテゴリの記事をすべて見る</a>
            </div>
        </div>
        <br>
    </div>
    <br>
    {% endfor %}
</div>
<br>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block content %}

<!-- Background image -->
<div class="p-5 text-center bg-image" style="
background-image: url('https://mdbootstrap.com/img/new/slides/041.jpg');
height: 300px;
">
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.6)">
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="text-white">
                <h1 class="mb-3">{{ request.site.siteconfig.top_title }}</h1>
                <h4 class="mb-3">{{ request.site.siteconfig.top_subtitle }}</h4>

            </div>
        </div>
    </div>
</div>
<!-- Background image -->
<div class="row">
    {% for item in post_list %}
    <div class="col-md-12">
        <div class="card">

            <div class="card-body">
                <div class="d-flex flex-row align-items-center">
                    <img src="https://mdbootstrap.com/img/new/standard/city/044.jpg" class="rounded-circle" alt="..."
                        width="50" height="50" />

                    <h4 class="card-title">{{ item.author }}</h4>
                </div>
                <small class="text-muted">{{ item.updated_at }}</small>
                <br>
                <h5 class="card-title">{{ item.title }}</h5>
                <p class="card-text">
                    カテゴリ:{{ item.category }}
                </p>
                <p class="card-text">
                    {{ item.content | safe | truncatechars_html:30 | urlizetrunc:30}}
                </p>
                {% if item.thumbnail %}
                <img src="{{ item.thumbnail.url }}" class="card-img-top" alt="{{ item.title }}"
                    style="width: 200px; height: 200px; object-fit: cover;" />
                {% endif %}
                <a href="{% url 'myapp:post_detail' item.id %}">
                    <div class="mask"></div>
                </a>
            </div>

        </div>
        <br>
    </div>
    {% endfor %}
</div>
{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <br>
        <h2 class="">ログイン</h2>
        <br>
        <form action="" class="" method="post">{% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            {{ field.label }}
            {{ field }}
            {{ field.errors }}
            <br>
            {% endfor %}
            <button type="submit" class="btn btn-primary">ログイン</button>
        </form>
        <br>
        <a href="{% url 'myapp:signupuser' %}">サインアップはこちら</a>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <br>
        <h2>ログアウト</h2>
        <br>
        <p>ログアウトしました</p>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<br>

myapp/templates/myapp/post_confirm_delete.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2 class="">ツイートの削除</h2>
        <br>
        <div class="alert alert-danger" role="alert">
            <form method="post">{% csrf_token %}
                <p>以下の内容を本当に削除しますか</p>
                <input type="submit" class="btn btn-outline-danger" value="削除する">
            </form>
        </div>
        <br>
        <p>タイトル</p>
        {{ object.title }}
        <hr>
        <p>内容</p>
        {{ object.content }}
        <br>
        <br>
        <br>
    </div>

</div>
{% endblock %}

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}

{% block content %}
<br>

<div class="row">

    <div class="col-md-9">
        <div class="card">

            <div class="card-body">
                <div class="d-flex flex-row align-items-center">
                    <img src="https://mdbootstrap.com/img/new/standard/city/044.jpg" class="rounded-circle" alt="..."
                        width="50" height="50" />

                    <h4 class="card-title">{{ object.author }}</h4>
                </div>
                <small class="text-muted">{{ object.updated_at }}</small>
                <br>
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text">
                    {{ object.content | safe | linebreaksbr | urlizetrunc:30}}
                </p>
                {% if object.thumbnail %}
                <img src="{{ object.thumbnail.url }}" class="card-img-top" alt="{{ item.title }}" />
                {% endif %}
                <br>
                <br>
                <a href="javascript:void(0);" onclick="window.history.back()" class="btn btn-outline-dark">戻る</a>
                {% if object.author == request.user %}
                <a href="{% url 'myapp:post_update' object.pk %}" class="btn btn-primary">更新</a>
                <a href="{% url 'myapp:post_delete' object.pk %}" class="btn btn-outline-danger">削除</a>
                {% else %}
                <a href="{% url 'myapp:like' object.pk %}" class="btn btn-primary">お気に入り({{ like_num }})</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <br>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ object.category }}</h5>
                <p>このカテゴリの他の記事</p>
            </div>
            <ul class="list-group">
                {% for item in category_posts %}
                <li class="list-group-item"><a href="{% url 'myapp:post_detail' item.pk %}">{{ item.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

</div>
<br>

{% endblock %}

myapp/templates/myapp/post_form.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2 class="">ツイート</h2>
        <br>
        <form action="" class="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
                <label>タイトル</label>
                {{ form.title }}
            </div>
            <br>

            <div class="form-group">
                <label>内容</label>
                {{ form.content }}
            </div>
            <br>
            <div class="form-group">
                <label>サムネイル</label>
                {{ form.thumbnail }}
            </div>
            <br>
            <div class="form-group">
                <label>カテゴリ</label>
                {{ form.category }}
            </div>
            <br>
            <button type="submit" class="btn btn-primary">投稿</button>
        </form>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/post_list.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2 class="">ツイート一覧</h2>
        <br>
        <table class="table">
            <thead>
                <tr>
                    <th>タイトル</th>
                    <th>内容</th>
                    <th>作成日時
                        <br> 更新日時
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for item in post_list %}
                <tr>
                    <td><a href="{% url 'myapp:post_detail' item.pk %}">{{ item.title }}</a></td>
                    <td>{{ item.content | safe }}</td>
                    <td>{{ item.created_at }}
                        <br>{{ item.updated_at }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        {% include 'myapp/pagination.html' %}
    </div>
</div>
{% endblock %}

myapp/templates/myapp/search.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2 class="">{{ freeword }}検索結果</h2>
        <br>
        <table class="table">
            <thead>
                <tr>
                    <th>タイトル</th>
                    <th>内容</th>
                    <th>作成日時</th>
                    <th>更新日時</th>
                </tr>
            </thead>
            <tbody>
                {% for item in search_list %}
                <tr>
                    <td><a href="{% url 'myapp:post_detail' item.pk %}">{{ item.title }}</a></td>
                    <td>{{ item.content }}</td>
                    <td>{{ item.created_at }}</td>
                    <td>{{ item.updated_at }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/signup.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <br>
        <h2 class="">サインアップ</h2>
        <br>
        <form action="" class="" method="post">{% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            {{ field.label }}
            {{ field }}
            {{ field.errors }}
            <br>
            {% endfor %}
            <button type="submit" class="btn btn-primary">サインアップ</button>
        </form>
        <br>
        <a href="{% url 'myapp:loginuser' %}">ログインはこちら</a>
    </div>
</div>
{% endblock %}